import Head from "next/head";
import Content from "../components/Content";
import Header from "../components/Header";
import { createContext, useReducer } from "react";

export const RootContext = createContext(null);

const initialState = {
  selectedTab: "Projects",
};

const reducerFunc = (state, action) => {
  switch (action.type) {
    case "setSelectedTab":
      return {
        ...state,
        selectedTab: action.payload,
      };
  }
};

export default function Home() {
  const [state, dispatch] = useReducer(reducerFunc, initialState);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootContext.Provider
        value={{
          state,
          dispatch,
        }}
      >
        <Header />
        <Content />
      </RootContext.Provider>
    </div>
  );
}
